#!/bin/bash

#PBS -q studenti
#PBS -l nodes=1:ppn=8
#PBS -N matrix_by_vector_2_thread_2000_x_20000
#PBS -o matrix_by_vector_2_thread_2000_x_20000.out
#PBS -e matrix_by_vector_2_thread_2000_x_20000.err

cat $PBS_NODEFILE

PBS_O_WORKDIR=$PBS_O_HOME/matrix_by_vector_project

export OMP_NUM_THREADS=2
export PSC_OMP_AFFINITY=TRUE
gcc -fopenmp -lgomp -o $PBS_O_WORKDIR/matrix_by_vector $PBS_O_WORKDIR/main.c

$PBS_O_WORKDIR/matrix_by_vector 2000 20000 1 1