#!/bin/bash

#PBS -q studenti
#PBS -l nodes=1:ppn=8
#PBS -N matrix_by_vector_hide_outputs
#PBS -o matrix_by_vector_hide_outputs.out
#PBS -e matrix_by_vector_hide_outputs.err

cat $PBS_NODEFILE

PBS_O_WORKDIR=$PBS_O_HOME/matrix_by_vector_project

export OMP_NUM_THREADS=6
export PSC_OMP_AFFINITY=TRUE
gcc -fopenmp -lgomp -o $PBS_O_WORKDIR/matrix_by_vector $PBS_O_WORKDIR/main.c

$PBS_O_WORKDIR/matrix_by_vector 10 10 1 1