#!/bin/bash

#PBS -q studenti
#PBS -l nodes=1:ppn=8
#PBS -N matrix_by_vector_8_thread_3000_x_30000
#PBS -o matrix_by_vector_8_thread_3000_x_30000.out
#PBS -e matrix_by_vector_8_thread_3000_x_30000.err

cat $PBS_NODEFILE

PBS_O_WORKDIR=$PBS_O_HOME/matrix_by_vector_project

export OMP_NUM_THREADS=8
export PSC_OMP_AFFINITY=TRUE
gcc -fopenmp -lgomp -o $PBS_O_WORKDIR/matrix_by_vector $PBS_O_WORKDIR/main.c

$PBS_O_WORKDIR/matrix_by_vector 3000 30000 1 1