#!/bin/bash

#PBS -q studenti
#PBS -l nodes=1:ppn=8
#PBS -N matrix_by_vector_4_thread
#PBS -o matrix_by_vector_4_thread.out
#PBS -e matrix_by_vector_4_thread.err

cat $PBS_NODEFILE

PBS_O_WORKDIR=$PBS_O_HOME/matrix_by_vector_project

export OMP_NUM_THREADS=4
export PSC_OMP_AFFINITY=TRUE
gcc -fopenmp -lgomp -o $PBS_O_WORKDIR/matrix_by_vector $PBS_O_WORKDIR/main.c

$PBS_O_WORKDIR/matrix_by_vector 1000 10000 1 1